### ISSUE TITLE
All groups should have a fixed prefix or suffix, for easy pattern matching (langgrp-*, kbrdgrp-* ? definitely not settled)

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/gut#43]

**Comment by snomos** [comment]
The background is that we need to group repos of the same type into subgroups, for various reasons. Presently, in svn, we have the following groups:

- startup
- experimental
- regular (unlabeled)
- private/closed-source
- external (using external sources via svn:external definitions)

In the future, additional groups could be:

- production
- beta/development

How to handle groups of languages is definitely not settled. The initial idea was to follow Apertium, and their use of meta-repos.

But maybe we won't use separate repos at all. @bbqsrc suggested to use github labels instead. Whatever we choose, I think some sort of metadata instead of a (meta) repo will be a more flexible and better solution.

The only reason to use a meta-repo à la Apertium, is to include in the meta-repo a Makefile, so that one can easily configure and build all and only those languages included in that group.

Whatever method we decide upon, the intended use of the grouping includes at least:

- inform linguists and other humans
- make it easy to clone just a specified subset of repos (ie all production or startup languages)
- determine inclusion into release packages/tools (e.g. all and only production languages are included in the release channel of the Divvun installer

**Comment by snomos** [comment]
This is now done using a combination of labels and git tags. No need to involve `gut`. Closed.
